### ISSUE TITLE
Error message appears for a while after recovering from seed

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#502]
More visible in android:
Recover from seed. As result error message appears for a while ('correspondent not found') and then success message change it

**Comment by yaryribero** [comment]
I couldn't reproduce. This correspondent could be one of our services (Discovery or  Funding), maybe this issue has been fixed with one of the many changes applied in this sprint.
@vkolt : can you give it a second try?

**Comment by vkolt** [comment]
Still happens. On Android it start to appears different one:
![IMG_4803.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6dbf9dcabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901dbf0bbb258a4f87b3be8949c3ee3f26f5c6.jpg)
